name: Process catalog

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Cache modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: |
          mkdir -p build
          go build -o build/scheduler-data ./...

      - name: Run
        env:
          S3_ACCOUNT_ID: ${{ secrets.S3_ACCOUNT_ID }}
          S3_SECRET: ${{ secrets.S3_SECRET }}
          S3_KEY_ID: ${{ secrets.S3_KEY_ID }}
        run: |
          ./build/scheduler-data

      - name: Commit & push changes
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
